// flow-typed signature: 266ac97f5775f38e202395ff098cc161
// flow-typed version: <<STUB>>/amazon-cognito-identity-js_v^1.20.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'amazon-cognito-identity-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'amazon-cognito-identity-js' {
    declare module .exports: any
;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'amazon-cognito-identity-js/dist/amazon-cognito-identity' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/dist/amazon-cognito-identity.min' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/dist/aws-cognito-sdk' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/dist/aws-cognito-sdk.min' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/enhance' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/AuthenticationDetails' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/AuthenticationHelper' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/BigInteger' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/CognitoAccessToken' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/CognitoIdToken' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/CognitoRefreshToken' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/CognitoUser' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/CognitoUserAttribute' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/CognitoUserPool' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/CognitoUserSession' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/DateHelper' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/index' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/es/StorageHelper' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/examples/babel-webpack/src/config' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/examples/babel-webpack/src/main' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/examples/babel-webpack/webpack.config.babel' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/AuthenticationDetails' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/AuthenticationHelper' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/BigInteger' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/CognitoAccessToken' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/CognitoIdToken' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/CognitoRefreshToken' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/CognitoUser' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/CognitoUserAttribute' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/CognitoUserPool' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/CognitoUserSession' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/DateHelper' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/index' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/lib/StorageHelper' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/AuthenticationDetails' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/AuthenticationHelper' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/BigInteger' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/CognitoAccessToken' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/CognitoIdToken' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/CognitoRefreshToken' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/CognitoUser' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/CognitoUserAttribute' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/CognitoUserPool' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/CognitoUserSession' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/DateHelper' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/index' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/src/StorageHelper' {
    declare module .exports: any
;
}

declare module 'amazon-cognito-identity-js/webpack.config' {
    declare module .exports: any
;
}

// Filename aliases
declare module 'amazon-cognito-identity-js/dist/amazon-cognito-identity.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/dist/amazon-cognito-identity'>
;
}
declare module 'amazon-cognito-identity-js/dist/amazon-cognito-identity.min.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/dist/amazon-cognito-identity.min'>
;
}
declare module 'amazon-cognito-identity-js/dist/aws-cognito-sdk.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/dist/aws-cognito-sdk'>
;
}
declare module 'amazon-cognito-identity-js/dist/aws-cognito-sdk.min.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/dist/aws-cognito-sdk.min'>
;
}
declare module 'amazon-cognito-identity-js/enhance.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/enhance'>
;
}
declare module 'amazon-cognito-identity-js/es/AuthenticationDetails.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/AuthenticationDetails'>
;
}
declare module 'amazon-cognito-identity-js/es/AuthenticationHelper.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/AuthenticationHelper'>
;
}
declare module 'amazon-cognito-identity-js/es/BigInteger.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/BigInteger'>
;
}
declare module 'amazon-cognito-identity-js/es/CognitoAccessToken.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/CognitoAccessToken'>
;
}
declare module 'amazon-cognito-identity-js/es/CognitoIdToken.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/CognitoIdToken'>
;
}
declare module 'amazon-cognito-identity-js/es/CognitoRefreshToken.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/CognitoRefreshToken'>
;
}
declare module 'amazon-cognito-identity-js/es/CognitoUser.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/CognitoUser'>
;
}
declare module 'amazon-cognito-identity-js/es/CognitoUserAttribute.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/CognitoUserAttribute'>
;
}
declare module 'amazon-cognito-identity-js/es/CognitoUserPool.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/CognitoUserPool'>
;
}
declare module 'amazon-cognito-identity-js/es/CognitoUserSession.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/CognitoUserSession'>
;
}
declare module 'amazon-cognito-identity-js/es/DateHelper.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/DateHelper'>
;
}
declare module 'amazon-cognito-identity-js/es/index.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/index'>
;
}
declare module 'amazon-cognito-identity-js/es/StorageHelper.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/es/StorageHelper'>
;
}
declare module 'amazon-cognito-identity-js/examples/babel-webpack/src/config.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/examples/babel-webpack/src/config'>
;
}
declare module 'amazon-cognito-identity-js/examples/babel-webpack/src/main.jsx' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/examples/babel-webpack/src/main'>
;
}
declare module 'amazon-cognito-identity-js/examples/babel-webpack/webpack.config.babel.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/examples/babel-webpack/webpack.config.babel'>
;
}
declare module 'amazon-cognito-identity-js/lib/AuthenticationDetails.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/AuthenticationDetails'>
;
}
declare module 'amazon-cognito-identity-js/lib/AuthenticationHelper.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/AuthenticationHelper'>
;
}
declare module 'amazon-cognito-identity-js/lib/BigInteger.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/BigInteger'>
;
}
declare module 'amazon-cognito-identity-js/lib/CognitoAccessToken.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/CognitoAccessToken'>
;
}
declare module 'amazon-cognito-identity-js/lib/CognitoIdToken.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/CognitoIdToken'>
;
}
declare module 'amazon-cognito-identity-js/lib/CognitoRefreshToken.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/CognitoRefreshToken'>
;
}
declare module 'amazon-cognito-identity-js/lib/CognitoUser.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/CognitoUser'>
;
}
declare module 'amazon-cognito-identity-js/lib/CognitoUserAttribute.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/CognitoUserAttribute'>
;
}
declare module 'amazon-cognito-identity-js/lib/CognitoUserPool.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/CognitoUserPool'>
;
}
declare module 'amazon-cognito-identity-js/lib/CognitoUserSession.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/CognitoUserSession'>
;
}
declare module 'amazon-cognito-identity-js/lib/DateHelper.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/DateHelper'>
;
}
declare module 'amazon-cognito-identity-js/lib/index.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/index'>
;
}
declare module 'amazon-cognito-identity-js/lib/StorageHelper.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/lib/StorageHelper'>
;
}
declare module 'amazon-cognito-identity-js/src/AuthenticationDetails.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/AuthenticationDetails'>
;
}
declare module 'amazon-cognito-identity-js/src/AuthenticationHelper.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/AuthenticationHelper'>
;
}
declare module 'amazon-cognito-identity-js/src/BigInteger.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/BigInteger'>
;
}
declare module 'amazon-cognito-identity-js/src/CognitoAccessToken.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/CognitoAccessToken'>
;
}
declare module 'amazon-cognito-identity-js/src/CognitoIdToken.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/CognitoIdToken'>
;
}
declare module 'amazon-cognito-identity-js/src/CognitoRefreshToken.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/CognitoRefreshToken'>
;
}
declare module 'amazon-cognito-identity-js/src/CognitoUser.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/CognitoUser'>
;
}
declare module 'amazon-cognito-identity-js/src/CognitoUserAttribute.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/CognitoUserAttribute'>
;
}
declare module 'amazon-cognito-identity-js/src/CognitoUserPool.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/CognitoUserPool'>
;
}
declare module 'amazon-cognito-identity-js/src/CognitoUserSession.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/CognitoUserSession'>
;
}
declare module 'amazon-cognito-identity-js/src/DateHelper.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/DateHelper'>
;
}
declare module 'amazon-cognito-identity-js/src/index.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/index'>
;
}
declare module 'amazon-cognito-identity-js/src/StorageHelper.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/src/StorageHelper'>
;
}
declare module 'amazon-cognito-identity-js/webpack.config.js' {
    declare module .exports: $Exports<'amazon-cognito-identity-js/webpack.config'>
;
}
